### ISSUE TITLE
Feature request: Debug Adapter Protocol (DAP) support.

### ISSUE THREAD

**Issue by carlosplanchon** [alexmojaki/birdseye#101]
I don't know if it would be possible given the actual structure of the code or this project, but I saw about DAP this morning and I remembered birdseye.

`The idea behind the Debug Adapter Protocol (DAP) is to abstract the way how the debugging support of development tools communicates with debuggers or runtimes into a protocol.`

https://microsoft.github.io/debug-adapter-protocol/

**Comment by alexmojaki** [comment]
I don't think they're conceptually compatible since birdseye isn't like a traditional debugger. It doesn't pause in the middle of execution at some breakpoint and wait for you to step through lines of code.
