### ISSUE TITLE
Using birdseye in interactive session

### ISSUE THREAD

**Issue by kootenpv** [alexmojaki/birdseye#50]
I want to be able to decorate functions in an interactive session.

When I try to evaluate such function, it will throw the exception:

    FileNotFoundError: [Errno 2] No such file or directory: '<ipython-input-7-01fc7a9cd10c>'

Initially I thought: go for an easy/hacky fix whenever the filename starts with `"<"`, then replace it with something like "interactive-session".

But I see you depend on it for the source code from `filename`. You could try `inspect.getsource(obj)` instead.

**Comment by alexmojaki** [comment]
Done! Upgrade and give it a go.

**Comment by kootenpv** [comment]
It works! Great job :)
