### ISSUE TITLE
VSCode extension

### ISSUE THREAD

**Issue by Almenon** [alexmojaki/birdseye#54]
Let me start off by saying great work! Your display is what I wish I had over in [AREPL](https://github.com/almenon/arepl-vscode), but I just return the final variables and call it a day :P

If I have time I might be able to work on a VSCode extension for birdseye, are you interested?

It looks pretty simple to implement, it would just require checking if the user has birdseye, spawning a process

> python -m birdseye

Then opening localhost:7777 in a preview pane.

I already have a [preview pane boilerplate](https://github.com/Almenon/vscode-extension-boilerplate) to extend from so that part's pretty much done.

Or theoretically that's how it would work, anyways.  I wouldn't be suprised if there was problems along the way.

**Comment by alexmojaki** [comment]
I am VERY interested 😃 

Since releasing I've realised integrations with other tools may be the best way to make birdseye more 'marketable' and bring in as many users as possible, and hopefully contributors. I've started working on a PyCharm plugin and after that will look at Jupyter notebooks and Jupyterlab. I've never used Visual Studio before so I'd love to have someone else tackle this.

**Comment by Almenon** [comment]
![vscode](https://user-images.githubusercontent.com/13080965/37751975-b8facdec-2d52-11e8-909c-db3235e77bb0.png)

:D 

Doing this was a breeze: I just cloned https://github.com/negokaz/vscode-live-server-preview and changed http://127.0.0.1:${port}${uri.path} to http://127.0.0.1:7777

Next step: open birdseye process when activating extension

**Comment by Almenon** [comment]
just finished the alpha version - you can install it manually from here:

https://github.com/Almenon/birdseye-vscode/releases/tag/v0.0.1

Still needs polish, but not bad for a couple hours worth of work.

**Comment by Almenon** [comment]
Fixed a few errors and got it on the marketplace! :tada:

https://marketplace.visualstudio.com/items?itemName=almenon.birdseye-vscode

Aside from some minor defects / enhancements (see [issues](https://github.com/Almenon/birdseye-vscode/issues)) it is pretty much done.

One item of note is that mac/linux users should set the pythonPath setting to python3 if using python 3.  I use python by default.... which happens to be python 2 on non-windows machines.  A bit unfortunate, that.

**Comment by alexmojaki** [comment]
Awesome, thanks so much for this!

I gave it a try and found a couple of problems for which I've opened some issues, but overall this is a great start.
