### ISSUE TITLE
want birdseye to be included in a pycon poster?

### ISSUE THREAD

**Issue by Almenon** [alexmojaki/birdseye#62]
I'll be going to Pycon in early May to do a poster presentation for AREPL ~ would you like to have birdseye be included in that poster?  It falls under the same category of visual debuggers, and I wouldn't mind giving some space on the poster to promote it. Thousands of people attend Pycon each year and it would be a great marketing opportunity for birdseye.

The poster is 36" by 48" - I could give you 9" by 11".  You can send me a mockup or pic or whatever for what you want it to look like.  The catch is that I'm planning on printing the poster by May 1, so that would not give you a lot of time :/  Sorry about the late notice.

I tried e-mailing you but I'm not sure if it went through spam filter.

**Comment by alexmojaki** [comment]
Sorry, I got the email, I'm just bad at replying. I appreciate the offer, but nah. I don't think a static poster can do birdseye justice.

**Comment by alexmojaki** [comment]
@Almenon please take a look at #64. I'm not sure if mentioning you there actually notified you

**Comment by Almenon** [comment]
mentioning there successfully notified me.
