### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/birdseye#64]
Current attempt:

![snake-birdseye](https://user-images.githubusercontent.com/3627481/39674320-43d29650-514a-11e8-948b-f5594f6ff1e2.png)

I'm not a graphic designer, so I'm hoping that someone more skilled can make this look better. For now, I'm thinking about the general concept.

@Almenon, what are your first impressions of this?

**Comment by Almenon** [comment]
The general idea is cool but it looks a bit simplistic.  Not that I'm one to judge, My [AREPL icon](https://github.com/Almenon/AREPL-vscode/blob/master/media/crappy8BitCat.png) is just as bad if not worse (I did it in MSPaint :P ).  

I would suggest using an already designed open source icon - for the VSCode extension I used a cool-looking [eye](https://github.com/Almenon/birdseye-vscode/blob/master/eye.png) I found.  

Or you can find a starving artist who is willing to design the icon for free? I wasn't able to find any website where artists offer open-source work for free but you could ask around.

If you want to change it yourself I would suggest getting rid of the snake ~ the name is birdseye, you could even literally have a picture of a [birds eye](https://www.google.com/search?q=birds+eye&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjWpJihs_HaAhWqj1QKHSqNCXEQ_AUICigB&biw=2275&bih=1134&dpr=0.9).  Or draw an eye and tile background with feathers?  Basically less snake more bird.

**Comment by alexmojaki** [comment]
Searching for [eagle eye](https://www.google.com/search?biw=1280&bih=631&tbm=isch&sa=1&ei=0i_vWp3sMoTHgAaGqLDACw&q=eagle+eye+logo&oq=eagle+eye&gs_l=img.3.0.35i39k1l2j0i67k1j0j0i67k1l3j0l3.77293.78608.0.81123.9.8.0.0.0.0.914.914.6-1.1.0....0...1c.1.64.img..8.1.914....0.5sLc5bdnjdY) gives lots of cool results along the lines of what I want. But I didn't want to deal with attribution issues. Here's a simpler version I made a while back:

![birdseye-logo](https://user-images.githubusercontent.com/3627481/39675693-3d6f4b04-515f-11e8-9689-2282ad022fcb.png)

Then later I had the idea of the snake and the colours to link it to Python. I thought it was cool but you're not the only person telling me to drop the snake.

[Searching on google again with the filter "Labeled for noncommercial reuse with modification"](https://www.google.com/search?q=eagle+eye+logo&tbs=sur:fm&tbm=isch&source=lnt&sa=X&ved=0ahUKEwj0z9e7xPHaAhXpLMAKHXVrBmkQpwUIHw&biw=1280&bih=631&dpr=1#imgrc=_) gives significantly poorer results, although I like [this first one](https://pixabay.com/en/owl-eye-animal-bird-eagle-wild-1207536/). I didn't like the markings on the side so I removed them:

![owl-eye](https://user-images.githubusercontent.com/3627481/39675809-d58797c4-5160-11e8-9d4b-1ba212fdf610.png)

Thoughts?

**Comment by alexmojaki** [comment]
Another idea:

![screen shot 2018-05-13 at 22 07 57](https://user-images.githubusercontent.com/3627481/39971371-2ccd4c10-56fa-11e8-865c-89a78c6df382.png)

This is inspired by the `@eye` decorator. The downside is that eventually I'd like to add ways to use birdseye without the decorator. On the other hand, it still gives a feeling of being related to code.

**Comment by alexmojaki** [comment]
Or another completely different idea:

![simple-geeky-owl](https://user-images.githubusercontent.com/3627481/39971743-e7f48d40-5700-11e8-9018-c74bab32ce13.jpg)

The idea is meant to be a bird that is also a programmer. A search for "geek owl" provides plenty of inspiration along these lines. The above is my simplified version of one image that I found.

**Comment by alexmojaki** [comment]
This is also pretty cool:

![eye-1185226_640](https://user-images.githubusercontent.com/3627481/39971771-a847078a-5701-11e8-9197-155a241b0efe.png)

But if we go in this direction it needs more bird.

@Almenon, I'd love some feedback or ideas.

**Comment by Almenon** [comment]
Just finished pycon, sorry for the delay. 

Where are you putting the logo?  I'm wondering what resolution it will end up being.

At 128x128 I think this eye looks best:

![eye1_128x128](https://user-images.githubusercontent.com/13080965/40095115-2b0e0afa-587f-11e8-95cb-8b5e7dd742f5.png)

BTW pycon would be a fantastic opportunity to market birdseye, in addition to being a great conference all around.  I would highly reccomend applying for a talk next year ~ you can ask for financial aid if you need travel assistance.

**Comment by alexmojaki** [comment]
That's one of the problems, I need a 16x16 version for the browser favicon and also the PyCharm plugin. It doesn't have to look great at that scale but I'd like it to not look terrible. For the eye it's not too bad:

![owl-eye 2](https://user-images.githubusercontent.com/3627481/40146689-c9b2f50c-5966-11e8-8c80-b8c0d9ed9899.png)

I actually presented birdseye in a 5-minute lightning talk at a PyCon before it was properly ready for release. People seemed interested at the time but it generated only a few stars on GitHub so I'm not sure how many people tried it out.

**Comment by Almenon** [comment]
Yeah the eye looks fine w/ 16x16.

One of the problems with the lightning talk is that there are so many speakers that it is hard to be remembered.  And some of the speakers are really good too.  The other problem being that 5 minutes is not a lot of time for a demo.

A full talk should give you much more time and a more interested crowd.

Which pycon did you present at?  I just gave a lightning talk at this years talk: 

https://www.youtube.com/watch?v=c-I0md_3fbQ&t=14s

Now compare that with the talk at 26:25 ..... you have to compete with some great speakers.

**Comment by ggcarlosr** [comment]
that such friends I am a graphic designer and I like to contribute with open source projects and I can help them.

**Comment by alexmojaki** [comment]
@ggcarlosr are you offering to design or suggest a logo?

**Comment by alexmojaki** [comment]
The logo has been incorporated into everything for a while now, so closing this. A friend suggested flipping it horizontally to make it more friendly because we subconsciously prefer things that go from left to right, and I agree.

@Almenon in the end I will give a talk on [birdseye and another package I recently released](https://za.pycon.org/talks/33-playing-with-pythons-internals/). Thanks for the encouragement.

**Comment by alexmojaki** [comment]
@Almenon update: here is the talk: https://www.youtube.com/watch?v=Wm47491S-Fo

**Comment by Almenon** [comment]
It was interesting to hear how birdseye worked. I wasn't expecting that everything would be wrapped in a before and after function.  In a early prototype of AREPL I tried a similar thing - I had a shortcut for wrapping the code in a print() so you could print out the value.  The same shortcut would wrap with print(dir()) if the line ended in a . as a rudimentary version of intellisense.

https://github.com/Almenon/AREPL-electron/blob/master/src/printDir.js

But like you said regex is not a proper solution for parsing source code. I recall there being some problems with my implementation - regex generally falls victim to nasty edge cases.

Anyways, one last thing: your icon for socerery is awesome. I love it! :D

![ss 2018-10-27 at 06 52 35](https://user-images.githubusercontent.com/13080965/47611035-8bd79880-da19-11e8-95cb-665c00d61a4d.jpg)
