### ISSUE TITLE
No module named 'birdseye', windows 10, jupyter lab

### ISSUE THREAD

**Issue by Dene33** [alexmojaki/birdseye#72]
Trying to use birdseye with `%load_ext birdseye` in jupyter lab, win 10. Getting error `ModuleNotFoundError: No module named 'birdseye'` On another machine with win 7 - everything's perfectly fine.

Tried different approaches - with conda, virtualenv, different python versions, etc. No result.

**Comment by alexmojaki** [comment]
Does `import birdseye` work in the same notebook? What about outside a notebook?

**Comment by Dene33** [comment]
> Does `import birdseye` work in the same notebook? What about outside a notebook?

`import birdseye` doesn't work inside notebook. Everything's fine outside.

**Comment by alexmojaki** [comment]
This sounds like an issue with your notebook setup that probably has nothing to do with birdseye. birdseye is a pretty normal package as far as pip install goes.

Do any other pip-installed packages behave like this?

Does `sys.version` have the same value both inside and outside the notebook? How does `sys.path` compare? What if you set `sys.path = <value outside notebook>` inside the notebook?

**Comment by Dene33** [comment]
> This sounds like an issue with your notebook setup that probably has nothing to do with birdseye. birdseye is a pretty normal package as far as pip install goes.
> 
> Do any other pip-installed packages behave like this?
> 
> Does `sys.version` have the same value both inside and outside the notebook? How does `sys.path` compare? What if you set `sys.path = <value outside notebook>` inside the notebook?

Thank you. I found a solution by changing `sys.version` to `'3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]'` from Python 3.7.

But on win7 machine everything's okay with sys.version of Python 3.7.  There is just the same virtual environment as on win10 machine. I don't get it why it works on one computer and doesn't on another. With other pip-installed packages everything's okay.
