### ISSUE TITLE
http://localhost:7777/ipython_call rejected conection 

### ISSUE THREAD

**Issue by skoll43** [alexmojaki/birdseye#77]
im extra virgin in programming haha and using on thonny, the thing is, the program open a browser windows and then, dont show how is supposed to, i even make:
0. my private ip dmz, turn down smartscreen (windows)
1 .antivirus defender on all his options
2. make exclusions for firewall, deactivated the firewall, changed the port to various numbers
3. open manually the ports on router, i mean, how unsecure my notebook is supposed to be?! 
   hahaha 

> ![image](https://user-images.githubusercontent.com/54006305/62839294-4279d200-bc56-11e9-8c70-a9a6c4c62af9.png)

packages in thonny: 
0. ![image](https://user-images.githubusercontent.com/54006305/62839347-f1b6a900-bc56-11e9-87bf-0d64b0efef20.png)
1. 
![image](https://user-images.githubusercontent.com/54006305/62839357-009d5b80-bc57-11e9-8be6-3d95c7129cb4.png)

the bottom of this, is that im trying to understand this code:
```
def tri_recursion(k):
  if(k>0):
    result = k+tri_recursion(k-2)
    print(result)
  else:
    result = 0
  return result

print("\n\nRecursion Example Results")
tri_recursion(6)
```

any help will be greatly appreciated, 
even links with google searches, I'm so lost haha

**Comment by alexmojaki** [comment]
You shouldn't have to change any security settings. The server is probably having trouble starting up and Thonny doesn't show server logs AFAIK. Try running `birdseye` or `python -m birdseye` in a command prompt outside Thonny, you may need to `pip install birdseye` first (I'm not sure if/how Thonny affects the system interpreter). Hopefully we can see some information to debug with then.

**Comment by skoll43** [comment]
hey! from cmd works, normal python installation, back to normal security settings, thonny uses his bundled portable python enviroment as i understand Thank you for the commands !!!

**Comment by alexmojaki** [comment]
Glad it works. Can you open an issue with Thonny? We should probably be figuring out a way to see those server logs in Thonny and fix whatever problem is there.
