### ISSUE TITLE
Compatability with python 3.8

### ISSUE THREAD

**Issue by giladbarnea** [alexmojaki/birdseye#80]
Hi,
Love this tool. I keep telling everyone about it.
Python 3.8 compatibility would be awesome!

Edit:
I forked it, changed nothing besides adding the `'Programming Language :: Python :: 3.8'` classifier inside `setup.py`, pip installed it locally and it works with 3.8 as is (which makes sense).

I felt silly creating a PR for adding a single line.

**Comment by alexmojaki** [comment]
I've been using it, the classifier is definitely not required, but I will add it.

**Comment by nicois** [comment]
The snoop package seems to believe this isn't 3.8 compatible. If this is an incorrect assertion I can raise a ticket over there.

```python
Traceback (most recent call last):
  File "route.py", line 73, in <module>
    def handle_change(change: ChangeType) -> None:
  File "/usr/local/lib/python3.8/site-packages/snoop/tracer.py", line 290, in __call__
    raise Exception("birdseye doesn't support this version of Python")
Exception: birdseye doesn't support this version of Python
```

**Comment by alexmojaki** [comment]
I'm glad to hear you guys enjoy these tools. This is all resolved now.
